package Usuarios_log;
// Generated 08-jun-2018 10:39:19 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nombre;
	private String password;
	private Set<Usuario> postsForIdFrom = new HashSet<Usuario>(0);
	private Set<Usuario> postsForIdTo = new HashSet<Usuario>(0);

	public Usuario() {
	}

	public Usuario(String nombre, String password) {
		this.nombre = nombre;
		this.password = password;
	}

	public Usuario(String nombre, String password, Set<Usuario> postsForIdFrom, Set<Usuario> postsForIdTo) {
		this.nombre = nombre;
		this.password = password;
		this.postsForIdFrom = postsForIdFrom;
		this.postsForIdTo = postsForIdTo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Usuario> getPostsForIdFrom() {
		return this.postsForIdFrom;
	}

	public void setPostsForIdFrom(Set<Usuario> postsForIdFrom) {
		this.postsForIdFrom = postsForIdFrom;
	}

	public Set<Usuario> getPostsForIdTo() {
		return this.postsForIdTo;
	}

	public void setPostsForIdTo(Set<Usuario> postsForIdTo) {
		this.postsForIdTo = postsForIdTo;
	}

}
